# Generated by Django 6.0.5 on 2026-06-02 21:55

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Final extras migration in NetBox 4.5.8; also an ancestor in 4.6.x.
        ('extras', '0134_owner'),
        ('netbox_rpc', '0006_seed_ssh_install_procedure'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rpcexecution',
            new_name='netbox_rpc__assigne_c5b587_idx',
            old_name='netbox_rpc_assigned_idx',
        ),
        migrations.RenameIndex(
            model_name='rpcexecution',
            new_name='netbox_rpc__status_06e5ac_idx',
            old_name='netbox_rpc_status_idx',
        ),
        migrations.AddField(
            model_name='rpcexecution',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='rpcexecutionevent',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='rpclinuxserviceallowlist',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='rpcprocedure',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='rpcexecution',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='rpcexecutionevent',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='rpclinuxserviceallowlist',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name='rpcprocedure',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
    ]
