# Generated by Django 6.1 on 2026-08-28

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0134_owner"),
        ("netbox_rpc", "0085_seed_dns_staging_deploy"),
    ]

    operations = [
        migrations.AddField(
            model_name="rpcprocedurecommand",
            name="tags",
            field=taggit.managers.TaggableManager(
                through="extras.TaggedItem",
                to="extras.Tag",
            ),
        ),
        migrations.AlterField(
            model_name="rpcprocedurecommand",
            name="custom_field_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=utilities.json.CustomFieldJSONEncoder,
            ),
        ),
    ]
